name: Push to PyPI
on:
  push:
    branches:
      - feature-prepare-for-release
#  release:
#    types: [released, prereleased]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature-prepare-for-release
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9 - 3.11'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.2.2
    - name: Install dependencies
      run: |
        poetry install --no-root
        pip list
    - name: Test Library
      run: |
        poetry run pytest
    - name: Set Package Release Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Update Library Version
      run: |
        poetry version ${{ env.RELEASE_VERSION }}
    - name: Build Library
      run: |
        poetry build
    - name: Publish to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_PASSWORD_FUNCX }}
        poetry publish
